### ISSUE TITLE
How to use on C# ?

### ISSUE THREAD

**Issue by ghost** [SmoLL-iCe/DotNetAobScanMemory#1]
`        

        private DotNetScanMemory_SmoLL scan = new DotNetScanMemory_SmoLL();
        private IntPtr[] founds;

        private void button1_Click(object sender, EventArgs e)
        {
            founds = scan.ScanArray(scan.GetPID("discord"), "44 00 6f 00 4 00 4e 00 65 00 74 00 41 00 6f 00 62 00 53 00 63 00 61 00 6e 00 4d 00 65 00 6d 00 6f 00 72 00 79 00");
            if ((founds.Count() > 0))
            {
                MessageBox.Show("Found !");
            }
        }`

Error:
https://image.noelshack.com/fichiers/2018/51/6/1545515730-capture.png
The arithmetic operation caused an overload.

**Comment by LuanDevecchi** [comment]
Hey, did you check your pattern?

on the 5th byte there's a '4', should be 04 huh?

**Comment by ghost** [comment]
What do you mean ?
Can you give an example ?

**Comment by SmoLL-iCe** [comment]
The project has been updated, and contains examples, see the examples contained in the repository.
