### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly

### ISSUE THREAD

**Issue by rkmiecik** [SmoLL-iCe/DotNetAobScanMemory#4]
When i try to compile the code i got the following error:

https://i.imgur.com/zinc7XH.png
![error](https://user-images.githubusercontent.com/24721224/126089639-392acb3d-ac57-4528-96bc-474b4f282149.png)

The code I'm using is the example. csharp_console

https://i.imgur.com/IJPmf3Y.png
![codeusing](https://user-images.githubusercontent.com/24721224/126089621-b6e0a169-7a2f-4a6c-b5a1-4cf7eb6869ae.png)

I'm using .NET Core as framework and VS2019 Community as IDE.

**Comment by SmoLL-iCe** [comment]
it's because the module is not close to the executable.
"System.IO.FileNotFoundException: 'Could not load file or assembly" is dotNetMemoryScan.dll

**Comment by rkmiecik** [comment]
Thank you!
